"use client";
import React, { useState, useEffect } from 'react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

const meals={1:['Pre: Bread + Honey + Banana + Whey','Post: Eggs + Toast','Lunch: Chicken 220g + Rice 100g','Snack: Yogurt + Fruit','Dinner: Oats Bowl'],2:['Pre: Bread + Jam + Banana + Whey','Post: Eggs + Potato','Lunch: Chicken + Rice + Rajma','Snack: Whey + Apple','Dinner: Paneer + Roti'],3:['Pre: Bread + Honey + Banana + Whey','Post: Eggs','Lunch: Paneer + Rice','Snack: Yogurt + Almonds','Dinner: Oats Bowl'],4:['Pre: 4 Bread + Honey + Banana + Whey','Post: Eggs + 350g Potato','Lunch: Chicken 220g + Rice 120g','Snack: Yogurt + Fruit','Dinner: Oats Bowl'],5:['Pre: Bread + Jam + Banana + Whey','Post: 4 Eggs','Lunch: Chicken 220g + 3 Roti + 50g Rice','Snack: Whey + Banana','Dinner: Oats Bowl'],6:['Pre: Bread + Honey + Banana + Whey','Post: Eggs + Toast','Lunch: Rajma Bowl + Rice 100g + Curd','Snack: Yogurt + Nuts','Dinner: Chicken 200g + 2 Roti'],7:['Breakfast: Oats + Whey + Fruit','Lunch: Chicken 220g + Rice 80g','Snack: Yogurt + Almonds','Dinner: Paneer 180g + 2 Roti + Salad']};
const workouts={1:['Incline DB Press 4x8','Smith Incline 3x8','Cable Fly 3x15','Lateral Raise 5x15','Pushdown 4x12'],2:['Pullups 4','Pulldown 4x10','Chest Supported Row 4x10','Rear Delt Fly 4x15','Incline Curl 4x10'],3:['Hack Squat 4x8','RDL 4x8','Walking Lunges 3x12','Leg Curl 4x12','Calves 5x15'],4:['Incline Smith 4x8','Wide Pulldown 4x10','Machine Chest Press 3x12','Lateral Raise 6x15','EZ Curl 4x10','Skullcrusher 4x10'],5:['Seated Lateral Raise 5x20','Cable Upright Row 3x15','Preacher Curl 4x12','Hammer Curl 3x12','Pushdown 4x12','OH Rope Extension 3x15'],6:['Incline Walk 20 min','Mobility 15 min','Abs Circuit 3 rounds','Light Arms Pump'],7:['Rest Day','Walk 8k Steps','Stretch 10 min','Meal Prep','Recovery Focus']};

function Card({children}){return <div className='rounded-2xl border border-white/10 bg-white/[0.04] backdrop-blur-md p-4 text-slate-100 shadow-[0_0_0_1px_rgba(255,255,255,0.03),0_12px_32px_rgba(0,0,0,0.45)]'>{children}</div>}
function Btn({children,onClick,active}){return <button onClick={onClick} className={`px-4 py-2 rounded-xl border transition-all duration-200 ${active?'border-white/70 bg-white text-slate-950 shadow-[0_0_18px_rgba(255,255,255,0.28)]':'border-white/15 bg-white/[0.03] text-slate-200 hover:bg-white/[0.08] hover:border-white/25'}`}>{children}</button>}

export default function Page(){
const today=new Date().getDay()===0?7:new Date().getDay();
const [day,setDay]=useState(today); const [logs,setLogs]=useState({}); const [weights,setWeights]=useState([]); const [bw,setBw]=useState(''); const [tab,setTab]=useState('meals'); const [mode,setMode]=useState('bulk');
useEffect(()=>{const l=localStorage.getItem('logs');const w=localStorage.getItem('weights'); if(l) setLogs(JSON.parse(l)); if(w) setWeights(JSON.parse(w));},[]);
useEffect(()=>localStorage.setItem('logs',JSON.stringify(logs)),[logs]); useEffect(()=>localStorage.setItem('weights',JSON.stringify(weights)),[weights]);
const addLog=(ex,val)=>{if(!val)return; setLogs({...logs,[ex]:[...(logs[ex]||[]),{d:new Date().toLocaleDateString(),v:val}]})};
const addWeight=()=>{if(!bw)return; setWeights([...weights,{d:new Date().toLocaleDateString(),v:Number(bw)}]); setBw('')};
const avg=weights.length?(weights.reduce((a,b)=>a+b.v,0)/weights.length).toFixed(1):'-'; const latest=weights.length?weights[weights.length-1].v:'-'; const macros=mode==='bulk'?'155P / 320C / 60F':'170P / 220C / 55F';
return <main className='min-h-screen bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.14),transparent_36%),radial-gradient(circle_at_80%_20%,rgba(255,255,255,0.08),transparent_32%),#020617] text-slate-200 p-6'><div className='max-w-6xl mx-auto space-y-6'>
<h1 className='text-3xl md:text-4xl font-semibold tracking-tight bg-gradient-to-r from-white via-slate-200 to-slate-400 bg-clip-text text-transparent'>RECOMP COMMAND CENTER</h1>
<div className='grid md:grid-cols-4 gap-3'>{[['Day','Day '+day],['Latest BW',latest],['Avg BW',avg],['Mode',mode]].map((x,i)=><Card key={i}><div className='text-xs uppercase tracking-[0.14em] text-gray-400'>{x[0]}</div><div className='text-2xl font-semibold mt-1'>{x[1]}</div></Card>)}</div>
<div className='flex flex-wrap gap-2'>{[1,2,3,4,5,6,7].map(d=><Btn key={d} onClick={()=>setDay(d)} active={day===d}>Day {d}</Btn>)}</div>
<div className='flex flex-wrap gap-2'>{['meals','workout','stats','coach'].map(t=><Btn key={t} onClick={()=>setTab(t)} active={tab===t}>{t}</Btn>)}</div>
{tab==='meals' && <Card><div className='space-y-2'>{meals[day].map((m,i)=><div key={i} className='text-gray-100/95'>{m}</div>)}</div></Card>}
{tab==='workout' && <Card><div className='space-y-4'>{workouts[day].map((ex,i)=><WorkoutRow key={i} ex={ex} last={logs[ex]?.slice(-1)[0]?.v} onSave={addLog}/>)}</div></Card>}
{tab==='stats' && <div className='grid md:grid-cols-2 gap-4'><Card><ResponsiveContainer width='100%' height={260}><LineChart data={weights}><XAxis dataKey='d' stroke='#94a3b8'/><YAxis stroke='#94a3b8'/><Tooltip contentStyle={{backgroundColor:'#0b1220',border:'1px solid rgba(148,163,184,0.28)',borderRadius:'0.75rem',backdropFilter:'blur(6px)'}} labelStyle={{color:'#f1f5f9'}}/><Line type='monotone' dataKey='v' stroke='#f8fafc' strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></Card><Card><input className='border border-white/20 bg-white/[0.03] text-slate-100 p-2 rounded-xl w-full mb-3 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-white/40' placeholder='Bodyweight kg' value={bw} onChange={e=>setBw(e.target.value)}/><Btn onClick={addWeight}>Log Weight</Btn><div className='mt-4 text-slate-200'>Macros: {macros}</div></Card></div>}
{tab==='coach' && <Card><div className='flex gap-2 mb-4'><Btn onClick={()=>setMode('bulk')} active={mode==='bulk'}>Bulk</Btn><Btn onClick={()=>setMode('cut')} active={mode==='cut'}>Cut</Btn></div><div className='space-y-2'><div>Macros: {macros}</div><div>{mode==='bulk'?'If weight stalls 14d: +150 kcal':'If weak during cut: add refeed day'}</div></div></Card>}
</div></main>}

function WorkoutRow({ex,last,onSave}){const [val,setVal]=useState(''); return <div className='border-b border-white/10 pb-3'><div className='font-medium text-slate-100'>{ex}</div><input className='border border-white/20 bg-white/[0.03] text-slate-100 p-2 rounded-xl w-full my-2 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-white/40' placeholder='25kg x10' value={val} onChange={e=>setVal(e.target.value)}/><div className='flex gap-2 items-center'><Btn onClick={()=>{onSave(ex,val);setVal('')}}>Save</Btn><span className='text-sm text-gray-400'>Last: {last||'No log'}</span></div></div>}
